import type { NextPage } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LoginContainer from './LoginContainer';
import { useRouter } from 'next/router';
import DisplayQuestionContainer from './DisplayQuestionContainer';
import LoginRequired from '@/utils/loginRequired';


const Home: NextPage = () => {

  const router = useRouter();
  try {
    LoginRequired();
  } catch (error) {
    console.error(error);
  }

  const handleClick = () => {
    router.push('/DisplayQuestionContainer');
  };
  return (
    <>
      <Head>
        <title>Poll App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div  >

<DisplayQuestionContainer></DisplayQuestionContainer>

</div>
     
    </>
  );
};

export default Home;