import type { NextPage } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LoginContainer from './LoginContainer';
import { useRouter } from 'next/router';


const Home: NextPage = () => {

  const router = useRouter();

  const handleClick = () => {
    router.push('/CreatePollContainer');
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div  >

<LoginContainer></LoginContainer>

</div>
     
    </>
  );
};

export default Home;
